import { Banknote, Landmark, ShoppingCart, CreditCard, ArrowLeftRight, Wallet, PackageCheck, HandCoins, Zap, Plus, ArrowDownToLine, CircleMinus, BarChart3, ChevronRight } from "lucide-react";
import { Link } from "react-router-dom";
import { formatCurrency } from "@/lib/format";
export type FinanceDay = { day: string; total: number; cash: number; card: number; bank: number; credit: number };
export type FinanceSummary = { days: FinanceDay[]; deposited: number; used: number; recorders: Record<string,string> };
type Account = { id: string; name: string; kind: string; balance: number; auto_receipts?: boolean; exclude_opening_float?: boolean };
const money = (n: number) => formatCurrency(Number(n));
export const maldivesDay = (value: string | Date) => new Intl.DateTimeFormat("en-CA", { timeZone: "Indian/Maldives", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value));
export const closingCash = (c: { opening_cash: number; cash_sales: number; deductions: number; counted_cash: number; recorded_expected?: number; difference?: number }) => {
  if (c.recorded_expected != null && c.difference != null) return { expected: Number(c.recorded_expected), difference: Number(c.difference) };
  const expected = Math.round((Number(c.opening_cash)+Number(c.cash_sales)-Number(c.deductions))*100)/100;
  return { expected, difference: Math.round((Number(c.counted_cash)-expected)*100)/100 };
};
export default function SalesFinanceOverview({ accounts, summary, day, openFloat, latestClosing, activeDrawers = 0, onAction }: { accounts: Account[]; summary: FinanceSummary; day: string; openFloat: number; latestClosing?: { counted_cash: number; closed_at: string; cashier_name: string }; activeDrawers?: number; onAction: (kind:string)=>void }) {
  const cash=accounts.find(a=>a.kind==='cash');
  const banks=accounts.filter(a=>a.kind==='bank');
  const today=summary.days.find(d=>d.day===day) ?? { total:0,cash:0,card:0,bank:0,credit:0 };
  const tiles=[
    {title:cash?'On Hand Cash':'Last Counted Drawer Cash',value:cash?.balance ?? latestClosing?.counted_cash,help:cash?(cash.exclude_opening_float?'Daily collections · opening float excluded':'Available outside open drawers'):latestClosing?`Counted ${new Date(latestClosing.closed_at).toLocaleString('en-GB',{timeZone:'Indian/Maldives',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})} · includes excess`:'No closed drawer recorded',Icon:Banknote,color:'emerald',action:cash?'deposit':'initialize'},
    {title:'Bank Account Balance',value:banks.length?banks.reduce((s,a)=>s+Number(a.balance),0):undefined,help:'All recorded bank accounts',Icon:Landmark,color:'blue',action:'bank_opening'},
    {title:"Today’s Total Sales",value:today.total,help:'All payment methods · selected date',Icon:ShoppingCart,color:'amber'},
    {title:"Today’s Card Payments",value:today.card,help:'Auto added to bank on closing',Icon:CreditCard,color:'emerald'},
    {title:"Today’s Bank Transfers",value:today.bank,help:'Auto added to bank on closing',Icon:ArrowLeftRight,color:'violet'},
    {title:"Today’s Cash Sales",value:today.cash,help:'Counted cash posted at closing',Icon:Wallet,color:'rose'},
    {title:'Total Deposited (Month)',value:summary.deposited,help:'From cash on hand to bank',Icon:PackageCheck,color:'emerald'},
    {title:'Money Used (Month)',value:summary.used,help:'Cash-outs, spending and bank fees',Icon:HandCoins,color:'amber'},
  ];
  const colors:Record<string,string>={emerald:'from-emerald-50 to-green-50 border-emerald-100 text-emerald-700',blue:'from-blue-50 to-sky-50 border-blue-100 text-blue-700',amber:'from-amber-50 to-yellow-50 border-amber-100 text-amber-700',violet:'from-violet-50 to-purple-50 border-violet-100 text-violet-700',rose:'from-rose-50 to-pink-50 border-rose-100 text-rose-700'};
  const days=Array.from({length:7},(_,i)=>{const d=new Date(`${day}T12:00:00+05:00`);d.setUTCDate(d.getUTCDate()-6+i);const key=maldivesDay(d);return summary.days.find(x=>x.day===key)??{day:key,cash:0,card:0,bank:0,credit:0,total:0};});
  const maximum=Math.max(1,...days.map(d=>Number(d.total)));
  const methods=[{label:'Cash Sales',value:Number(today.cash),color:'#249b68'},{label:'Card Payments',value:Number(today.card),color:'#2188d8'},{label:'Bank Transfers',value:Number(today.bank),color:'#f4a51c'},{label:'Credit Sales',value:Number(today.credit),color:'#8760dc'}];
  const total=methods.reduce((s,m)=>s+m.value,0);let position=0;
  const panel='rounded-xl border border-stone-200/80 bg-white p-4 shadow-sm';
  return <>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{tiles.map(t=><button type="button" disabled={!t.action} onClick={()=>t.action&&onAction(t.action)} key={t.title} className={`flex items-center gap-3 rounded-xl border bg-gradient-to-br p-4 text-left shadow-sm disabled:cursor-default ${colors[t.color]}`}><span className="rounded-2xl bg-white/80 p-3 shadow-sm"><t.Icon size={23}/></span><span className="min-w-0 flex-1"><span className="block text-xs font-medium text-slate-700">{t.title}</span><strong className="my-1 block text-lg font-bold tracking-tight text-slate-950">{t.value===undefined?'Not set up':money(t.value)}</strong><span className="block text-[11px] text-slate-600">{t.help}</span></span>{t.action&&<ChevronRight size={15}/>}</button>)}</div>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_1fr_.8fr]">
      <section className={panel}><h2 className="flex items-center gap-2 text-sm font-bold"><BarChart3 size={17}/>Sales Overview <span className="ml-auto text-xs font-normal text-slate-500">Last 7 days</span></h2><div className="mt-5 flex h-40 items-end gap-3 border-b px-2" aria-label="Sales over the last seven days">{days.map(d=><div key={d.day} className="flex h-full min-w-0 flex-1 flex-col justify-end"><div className="flex flex-col-reverse overflow-hidden rounded-t" style={{height:`${Number(d.total)/maximum*100}%`,minHeight:Number(d.total)?3:0}} title={`${d.day}: ${money(d.total)}`}>{[d.cash,d.card,d.bank,d.credit].map((v,i)=><div key={i} style={{background:methods[i].color,flex:Number(v)}}/>)}</div></div>)}</div><div className="mt-2 flex gap-3 px-2">{days.map(d=><span key={d.day} className="min-w-0 flex-1 text-center text-[10px] text-slate-500">{new Date(`${d.day}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span>)}</div><div className="mt-4 flex flex-wrap justify-center gap-3">{methods.map(m=><span key={m.label} className="flex items-center gap-1 text-[10px]"><i className="h-2 w-2 rounded-sm" style={{background:m.color}}/>{m.label}</span>)}</div></section>
      <section className={panel}><h2 className="flex items-center gap-2 text-sm font-bold"><CreditCard size={17}/>Sales by Payment Method</h2><div className="mt-5 flex flex-wrap items-center justify-center gap-4"><div className="relative h-36 w-36 shrink-0"><svg viewBox="0 0 100 100" className="h-full w-full -rotate-90" role="img" aria-label="Payment method shares"><circle cx="50" cy="50" r="39" fill="none" stroke="#edf0ed" strokeWidth="16"/>{methods.map(m=>{const length=total?m.value/total*245.04:0;const offset=position;position+=length;return <circle key={m.label} cx="50" cy="50" r="39" fill="none" stroke={m.color} strokeWidth="16" strokeDasharray={`${length} ${245.04-length}`} strokeDashoffset={-offset}/>;})}</svg><div className="absolute inset-0 flex flex-col items-center justify-center"><strong className="text-sm">{money(total)}</strong><span className="text-[10px] text-slate-500">Total Sales</span></div></div><div className="min-w-32 flex-1 space-y-3">{methods.filter(m=>m.value||m.label!=='Credit Sales').map(m=><div key={m.label} className="text-xs"><div className="flex items-center gap-2"><i className="h-2 w-2 rounded-full" style={{background:m.color}}/>{m.label}</div><div className="ml-4 mt-1 flex justify-between gap-2 font-semibold">{money(m.value)}<span className="font-normal text-slate-500">{total?(m.value/total*100).toFixed(1):'0'}%</span></div></div>)}</div></div></section>
      <section className={panel}><h2 className="mb-3 flex items-center gap-2 text-sm font-bold"><Zap size={17}/>Quick Actions</h2><div className="space-y-2"><Link to="/cash-drawer" className="flex items-center gap-2 rounded-lg bg-emerald-900 px-3 py-2.5 text-xs font-medium text-white"><Plus size={16}/>Record Cash Drawer Closing</Link><button onClick={()=>onAction('deposit')} className="flex w-full items-center gap-2 rounded-lg bg-amber-600 px-3 py-2.5 text-xs font-medium text-white"><Landmark size={16}/>Deposit On Hand Cash to Account</button><button onClick={()=>onAction('bank_expense')} className="flex w-full items-center gap-2 rounded-lg bg-amber-50 px-3 py-2.5 text-xs text-amber-900"><HandCoins size={16}/>Use Money (Cash / Bank)</button><button onClick={()=>onAction('bank_opening')} className="flex w-full items-center gap-2 rounded-lg bg-emerald-100 px-3 py-2.5 text-xs text-emerald-900"><Plus size={16}/>Add Bank Account</button><a href="#finance-history" className="flex items-center gap-2 rounded-lg bg-sky-50 px-3 py-2.5 text-xs text-slate-700"><BarChart3 size={16}/>View Transactions</a></div></section>
    </div>
    <div className="grid gap-4 lg:grid-cols-[1.2fr_1fr]"><section className={panel}><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-bold"><Landmark size={17}/>Bank Accounts</h2><button onClick={()=>onAction('bank_opening')} className="rounded bg-emerald-900 px-2 py-1 text-xs text-white">+ Add Bank Account</button></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{banks.map(a=><div key={a.id} className="rounded-lg border border-stone-200 p-3"><Landmark size={20} className="mb-2 text-blue-600"/><p className="text-sm font-semibold">{a.name}</p><p className="mt-1 text-[10px] text-slate-500">{a.auto_receipts?'Automatic receiving account':'Bank account'}</p><strong className="mt-1 block text-sm">{money(a.balance)}</strong></div>)}</div>{!banks.length&&<p className="mt-4 text-sm text-slate-500">Add your bank and its actual opening balance to enable automatic credits.</p>}</section><section className={panel}><h2 className="flex items-center gap-2 text-sm font-bold"><Banknote size={17}/>On Hand Cash Management</h2><div className="mt-4 flex flex-wrap items-center gap-3"><div className="flex-1 rounded-lg bg-emerald-50 p-3"><p className="text-xs">{cash ? "Current On Hand Cash" : "Last Actual Drawer Cash"}</p><strong className="mt-1 block text-xl">{cash?money(cash.balance):latestClosing?money(latestClosing.counted_cash):'No count recorded'}</strong></div><button onClick={()=>onAction('deposit')} className="flex items-center gap-2 rounded-lg bg-amber-600 px-3 py-3 text-xs text-white"><ArrowDownToLine size={15}/>Deposit to Bank</button><button onClick={()=>onAction('cash_expense')} className="flex items-center gap-2 rounded-lg bg-rose-100 px-3 py-3 text-xs text-rose-800"><CircleMinus size={15}/>Use Cash</button></div><p className="mt-3 text-xs text-slate-500">{cash?.exclude_opening_float ? <>Collected cash = actual closing cash − opening float − recorded deposits / spending + incoming cash. A negative balance is a deficit.</> : cash ? <>Opening float in active drawers: {money(openFloat)}. Returned once with counted cash at closing.</> : <>Latest saved count, including excess / shortage. {activeDrawers > 0 ? `${activeDrawers} drawer(s) are open; current cash is not yet counted.` : "Cash held separately and later unrecorded movements are not included."}</>}</p></section></div>
  </>;
}
